# Generated by Django 3.0.8 on 2021-01-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classmate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='started_from',
        ),
    ]
